# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170824_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '未发表'), (1, '已发表')], default=1, verbose_name='发布状态'),
        ),
    ]
