# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170827_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_time', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
